version: '2'
services:
  moodle4_mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './moodle4_mariadb_data:/bitnami/mariadb'
  moodle4_moodle:
    image: docker.io/bitnami/moodle:4
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=moodle4_mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=lucasfrias
      - MOODLE_PASSWORD=Luquitas0612
      - MOODLE_SITE_NAME=Moodle Test
      - MOODLE_LANG=es
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle4_moodle:/bitnami/moodle'
      - './moodle4_moodledata:/bitnami/moodledata'
    depends_on:
      - moodle4_mariadb
  moodle3_mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './moodle3_mariadb_data:/bitnami/mariadb'
  moodle3_moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '8081:8080'
      - '8444:8443'
    environment:
      - MOODLE_DATABASE_HOST=moodle3_mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=lucasfrias
      - MOODLE_PASSWORD=Luquitas0612
      - MOODLE_SITE_NAME=Moodle Test
      - MOODLE_LANG=es
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './moodle3_moodle:/bitnami/moodle'
      - './moodle3_moodledata:/bitnami/moodledata'
    depends_on:
      - moodle3_mariadb